name: Update DNS Blocklists

on:
  schedule:
    - cron: '0 0 * * *' # Chạy vào 00:00 UTC hàng ngày
  workflow_dispatch: # Cho phép bấm chạy thủ công

permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run update script
        run: |
          chmod +x update_lists.sh
          ./update_lists.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: blocklists and allowlists [skip ci]"
          file_pattern: 'mosdns-x/*.txt'
          branch: ${{ github.ref }}
